apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: streaming-app-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kstreams
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Pods
    pods:
      metricName: custom.googleapis.com|consumer_lag_game_frame_rs
      targetAverageValue: 5000
  - type: Pods
    pods:
      metricName: custom.googleapis.com|consumer_lag_game_frame_rq
      targetAverageValue: 5000

