apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cloud-fighter-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloud-fighter
  minReplicas: 1
  maxReplicas: 4
  metrics:
#  - type: External
#    external:
#      metricName: consumer_lag_game_frame_rs
#      metricSelector:
#        matchLabels:
#          metric: records-lag
#      targetAverageValue: 99000
  - type: Pods
    pods:
      metricName: custom.googleapis.com|consumer_lag_game_frame_rq
#      metricSelector:
#        matchLabels:
#          metric: records-lag
      targetAverageValue: 5000

