apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datagen
  namespace: default
  labels:
    app: datagen
spec:
  selector:
    matchLabels:
      app: datagen
  template:
    metadata:
      labels:
        app: datagen
    spec:
      containers:
      - name: datagen-app
        image: gcr.io/cloud-fighter-101/kos-datagen-app:latest
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: confluent-secrets
              key: api-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: confluent-secrets
              key: secret-key
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: confluent-secrets
              key: bootstrap-servers
        - name: SCHEMA_REGISTRY
          value: http://schema-registry-service:80
